In [3]:
%pip install folium
%pip install wget
%pip install shapely
%pip install geopandas
import folium
import wget
import pandas as pd
from geopy.geocoders import Nominatim
import matplotlib.pyplot as plt
import random
from shapely.geometry import Point, LineString
import geopandas as gpd
import numpy as np

Defaulting to user installation because normal site-packages is not writeable
Collecting folium
  Using cached folium-0.20.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting branca>=0.6.0 (from folium)
  Using cached branca-0.8.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: jinja2>=2.9 in c:\programdata\anaconda3\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from folium) (2.1.3)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in c:\programdata\anaconda3\lib\site-packages (from folium) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2025.8.3)
Using cached folium-0.20.0-py2.py3-none-any.whl (113 kB)
Using cached branca-0.8.2-py3-none-any.whl (26 kB)
Installing collected packages: branca, folium

   -------------------- ------------------- 1/2 [folium]
   -------------------- ------------------- 1/2 [folium]
   -------------------- ------------------- 1/2 [folium]
   -------------------- ------------------- 1/2 [folium]
   -------------------- ------------------- 1/2 [folium]
   ---------------------------------------- 2/2 [folium]

Successfully installed branca-0.8.2 folium-0.20.0
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: wget
  Building wheel for wget (setup.py): started
  Building wheel for wget (setup.py): finished with status 'done'
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9683 sha256=591069fd36f1acc87644efc38b3a16e7cc6911ce314b981b50d0a0f573c70047
  Stored in directory: c:\users\razer-frey\appdata\local\pip\cache\wheels\8a\b8\04\0c88fb22489b0c049bee4e977c5689c7fe597d6c4b0e7d0b6a
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2
Note: you may need to restart the kernel to use updated packages.

  DEPRECATION: Building 'wget' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'wget'. Discussion can be found at https://github.com/pypa/pip/issues/6334

Defaulting to user installation because normal site-packages is not writeable
Collecting shapely
  Using cached shapely-2.1.2-cp313-cp313-win_amd64.whl.metadata (7.1 kB)
Requirement already satisfied: numpy>=1.21 in c:\programdata\anaconda3\lib\site-packages (from shapely) (2.1.3)
Using cached shapely-2.1.2-cp313-cp313-win_amd64.whl (1.7 MB)
Installing collected packages: shapely
Successfully installed shapely-2.1.2
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Collecting geopandas
  Using cached geopandas-1.1.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: numpy>=1.24 in c:\programdata\anaconda3\lib\site-packages (from geopandas) (2.1.3)
Collecting pyogrio>=0.7.2 (from geopandas)
  Using cached pyogrio-0.12.1-cp313-cp313-win_amd64.whl.metadata (6.0 kB)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from geopandas) (2.2.3)
Collecting pyproj>=3.5.0 (from geopandas)
  Using cached pyproj-3.7.2-cp313-cp313-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: shapely>=2.0.0 in c:\users\razer-frey\appdata\roaming\python\python313\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.8.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Using cached geopandas-1.1.3-py3-none-any.whl (342 kB)
Using cached pyogrio-0.12.1-cp313-cp313-win_amd64.whl (22.9 MB)
Using cached pyproj-3.7.2-cp313-cp313-win_amd64.whl (6.3 MB)
Installing collected packages: pyproj, pyogrio, geopandas

   ---------------------------------------- 0/3 [pyproj]
   ---------------------------------------- 0/3 [pyproj]
   ---------------------------------------- 0/3 [pyproj]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   ---------------------------------------- 3/3 [geopandas]

Successfully installed geopandas-1.1.3 pyogrio-0.12.1 pyproj-3.7.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script pyproj.exe is installed in 'C:\Users\Razer-Frey\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

ModuleNotFoundError: No module named 'geopy'

In [4]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

In [5]:
spacex_csv_file = wget.download('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv')
spacex_df=pd.read_csv(spacex_csv_file)

In [6]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

In [7]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [8]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

In [9]:
CCAFS_coordinate = [28.562302,-80.577356]
CCAFSS_coordinate = [28.563197,-80.57682]
KSC_coordinate = [28.573255,-80.646895]
VAFB_coordinate = [34.632834,-120.610746]

# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle_CCAFS = folium.Circle(CCAFS_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NACCAFS LC-40'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker_CCAFS = folium.map.Marker(
    CCAFS_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40',
        )
    )
site_map.add_child(circle_CCAFS)
site_map.add_child(marker_CCAFS)

# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle_CCAFSS = folium.Circle(CCAFSS_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('CAFS SLC-40'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker_CCAFSS = folium.map.Marker(
    CCAFSS_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CAFS SLC-40',
        )
    )
site_map.add_child(circle_CCAFSS)
site_map.add_child(marker_CCAFSS)

# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle_KSC = folium.Circle(KSC_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('KSC LC-39A'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker_KSC = folium.map.Marker(
    KSC_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A',
        )
    )
site_map.add_child(circle_KSC)
site_map.add_child(marker_KSC)

# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle_VAFB = folium.Circle(VAFB_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('VAFB SLC-4E'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker_VAFB = folium.map.Marker(
    VAFB_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E',
        )
    )
site_map.add_child(circle_VAFB)
site_map.add_child(marker_VAFB)

In [10]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

In [11]:
marker_cluster = MarkerCluster()

In [13]:
# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red
spacex_df['marker_color'] = ''
# Function to assign color to launch outcome
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'
    
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

In [14]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for i, record in spacex_df.iterrows():
    marker = folium.Marker(location = (spacex_df.iloc[i]['Lat'],spacex_df.iloc[i]['Long']), icon = folium.Icon(color='white', icon_color =spacex_df.iloc[i]['marker_color'])).add_to(marker_cluster)
    marker_cluster.add_child(marker)

site_map

In [15]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

In [16]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [17]:
# find coordinate of the closet coastline
lat = 28.56221
long = -80.56777
distance_coastline = calculate_distance(launch_sites_df.iloc[0]["Lat"], launch_sites_df.iloc[0]["Long"], lat, long)
distance_coastline

0.9365874197351569

In [18]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 

distance_marker = folium.Marker(
    [lat, long],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
        )
    )

In [19]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
coordinates = [[lat,long],[launch_sites_df.iloc[0]["Lat"], launch_sites_df.iloc[0]["Long"]]]
lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

In [20]:
# Create a marker with distance to Melbourne Florida
# Draw a line between the marker to the launch site
lat_melbourne = 28.070061
long_melbourne = -80.561104
distance_melbourne = calculate_distance(launch_sites_df.iloc[0]["Lat"], launch_sites_df.iloc[0]["Long"], lat_melbourne, long_melbourne)
distance_melbourne

54.77500486370945

In [21]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 

distance_marker_melbourne = folium.Marker(
    [lat_melbourne, long_melbourne],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#2f40f8;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_melbourne),
        )
    )

In [22]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
to_melbourne = [[lat_melbourne,long_melbourne],[launch_sites_df.iloc[0]["Lat"], launch_sites_df.iloc[0]["Long"]]]
lines_melbourne=folium.PolyLine(locations=to_melbourne, weight=1)
site_map.add_child(distance_marker_melbourne)
site_map.add_child(lines_melbourne)